name: workflow

on:
  push:
    branches:
      - main

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.ATLAS_USERNAME }}
          password: ${{ secrets.ATLAS_PASSWORD }}